# Generated by Django 3.1.7 on 2021-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=15)),
                ('locale', models.CharField(max_length=50)),
                ('is_seller', models.BooleanField(default=False)),
                ('gmap', models.CharField(max_length=100)),
            ],
        ),
    ]
