# Generated by Django 3.1.7 on 2021-05-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('elec', 'electronic'), ('lap', 'laptops')], max_length=5)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('seller_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_pics')),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('keywords', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profiles',
            name='gmap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
