# Generated by Django 3.1.7 on 2021-05-15 04:15

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210515_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
