# Generated by Django 3.2.3 on 2021-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210515_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('el01', 'General Electronics'), ('el02', 'Electronics-Smartphones'), ('el03', "Electronics-PC's"), ('el04', 'Electronics-PC Components'), ('el05', 'Electronics-Laptops'), ('fs01', 'Fashion-Mens'), ('fs02', 'Fashion-Womens'), ('fs03', 'Fashion-Unisex'), ('fs04', 'Fashion-Shoes')], max_length=5),
        ),
    ]
