# Generated by Django 3.2.3 on 2021-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('General Electronics', 'General Electronics'), ('Electronics-Smartphones', 'Electronics-Smartphones'), ("Electronics-PC's", "Electronics-PC's"), ('Electronics-PC Components', 'Electronics-PC Components'), ('Electronics-Laptops', 'Electronics-Laptops'), ('Fashion-Mens', 'Fashion-Mens'), ('Fashion-Womens', 'Fashion-Womens'), ('Fashion-Unisex', 'Fashion-Unisex'), ('Fashion-Shoes', 'Fashion-Shoes')], max_length=50),
        ),
    ]
