# Generated by Django 3.1.7 on 2021-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_offer',
            field=models.TextField(default='No offer available.'),
        ),
    ]
