# Generated by Django 3.1.7 on 2021-06-08 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_products_available_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
