# Generated by Django 3.1 on 2021-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210608_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Seller'),
        ),
    ]
