# Generated by Django 3.1.7 on 2021-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210608_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='pan',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Do you want to sell with eMPORIUM?'),
        ),
    ]
