# Generated by Django 3.1 on 2021-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210626_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='pan',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
