# Generated by Django 3.1.7 on 2021-06-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210626_1251'),
        ('home', '0013_auto_20210626_1301'),
    ]

    operations = [
    ]
