# Generated by Django 3.1.7 on 2021-07-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20210626_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Electronic Devices', 'Electronic Devices'), ('Electronic Accessories', 'Electronic Accessories'), ('TV & Home Appliances', 'TV & Home Appliances'), ('Health & Beauty', 'Health & Beauty'), ('Babies & Toys', 'Babies & Toys'), ('Groceries & Pets', 'Groceries & Pets'), ('Home & Lifestyle', 'Home & Lifestyle'), ("Women's Fashion", "Women's Fashion"), ("Men's Fashion", "Men's Fashion"), ('Watches & Accessories', 'Watches & Accessories'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Automotive & Motorbike', 'Automotive & Motorbike')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Do you want to sell with eMPORIUM?'),
        ),
    ]
