# Generated by Django 3.1.7 on 2021-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('order_date', models.DateTimeField()),
                ('buyer_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pro', 'Processing'), ('del', 'Delivering')], max_length=10)),
                ('amount', models.FloatField()),
                ('received_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('product_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('provider', models.CharField(choices=[('e', 'eSewa'), ('cod', 'Cash On Delivery')], max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('y', 'Paid'), ('n', 'Not Paid')], max_length=10)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
    ]
