# Generated by Django 3.1.7 on 2021-05-24 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_products_stock'),
        ('orderapp', '0003_auto_20210522_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='payment_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.payment_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.profiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
